[tool.poetry]
name = "fastzdp-api"
version = "0.1.0"
description = ""
authors = ["张大鹏 <1156956636@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
